name: Rust CI Test

on:
  push:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust-version: [nightly]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Source code spell checker
      uses: crate-ci/typos@master
